### PR TITLE
Preparing for further maintenance

### PR DESCRIPTION
**Pull request by chadowo**
Hello there! I've got changes and questions that I'll appreciate I can discuss here.

## Changes

Minimal as of now, the most notables being:

- the most notable one is that specs now pass, however those are superficial changes, there's a *lot* of specs to update in conformation with the new rspec syntax
- replaced some deprecated functionality from ruby with the newer one
- ironed out Rake tasks and gemspec
- new `README.md` with some information about the fork, the old one is still there as `README.old.rdoc`
- added rubocop on `Gemfile`, in preparation for use after updating specs

## Things To Do

There's still a lot to do, my plan as of now consists of:

1. update the specs to the new rspec
2. update the library source
3. documenting everything with YARD
4. update the examples (add some new ones too!)

So I got quite some things to keep myself occupied

## Questions

I'm quite new to developing gems, moreover forks of so I wanted to ask

- do we need to update the `author` and `email` fields under `chingu.gemspec`, if so what should I put there?
- how do we release this gem to the public?

---

Thanks.

### CODE REVIEW

**Comment by jlnr** [comment]
Thanks for this PR! It would be splendid if we could release another version of Chingu. I know it's going to be a bit annoying, but do you think you can maybe split this up into more PRs? One that just removes trailing whitespace everywhere and then maybe one for the RSpec fixes and one for meta things like removing rubyforge from the gemspec?

**Comment by chadowo** [comment]
Yes! don't worry, whatever is more manageable for you!

**Comment by chadowo** [comment]
I'm gonna make a new branch on my end, `rspec-fixes` where I'll update rspec to the new syntax, after that's done I'll send you a pull request, then later comes the source code of the library. Is that ok with you?

And talking about meta, I've decided to kill the following dependencies:
- [Watchr](https://github.com/mynyml/watchr) (**inactive**)
- [Rcov](https://github.com/relevance/rcov) (**old**)

watchr provides continuous  testing and rcov code coverage, so there's nothing crucial about them (thats it, if you don't want that features), If we need them in any case I'll look for modern alternatives

**Comment by chadowo** [comment]
> I'm gonna make a new branch on my end, rspec-fixes where I'll update rspec to the new syntax, after that's done I'll send you a pull request [...]

Never mind that, I've opened the request so you can have it at hand (#3)

**Comment by chadowo** [comment]
I'll drop this PR since all relevant changes have already been merged with #3, and it wouldn't make a lot of sense to merge the other ones in this PR, I'll continue to work on the library internals on the `modernize-ruby` branch

**Pull request closed without merging**
